# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca6a74415365317960cc997f2f4ea023187c98763b9ffe33cd17e2185a717b330741d9957344059f609dd8a61a7e989fc43d69a66ac2af57a6ac62c0ba99ed4b

test:
  secret_key_base: c1368fbb3df76296dec3f57202544e8936fa98c0c1190344a55aff816869f620470c6b43b89d5eb8893a77a1a22d3ef97b9a21a10775e1d4ce6c48311f018f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
